# Generated by Django 5.1.4 on 2026-05-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_referee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='best_of',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
