# Generated by Django 5.1.4 on 2026-05-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('format', models.CharField(choices=[('Top4', 'Top4'), ('Top8', 'Top8'), ('Premium/Star', 'Premium/Star')], max_length=32)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Live', 'Live'), ('Completed', 'Completed')], default='Draft', max_length=16)),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
    ]
