# Generated by Django 5.1.4 on 2026-05-10 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('points_scored', models.PositiveIntegerField(default=0)),
                ('points_given', models.PositiveIntegerField(default=0)),
                ('net_run_rate', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('pool_type', models.CharField(blank=True, choices=[('none', 'None'), ('premium', 'Premium'), ('star', 'Star')], max_length=10, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['rank', '-wins', '-net_run_rate', '-points_scored'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'team', 'pool_type'), name='uniq_team_standing_per_tournament_pool')],
            },
        ),
    ]
